# Generated by Django 3.0.2 on 2020-02-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inappmessage',
            name='content',
        ),
        migrations.AddField(
            model_name='inappmessage',
            name='message',
            field=models.TextField(default='hey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inappmessage',
            name='status',
            field=models.CharField(default='unread', max_length=10),
        ),
        migrations.AddField(
            model_name='inappmessage',
            name='title',
            field=models.CharField(default='title', max_length=512),
            preserve_default=False,
        ),
    ]
