# Generated by Django 3.0.2 on 2020-02-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(default='', max_length=30),
        ),
    ]
