# Generated by Django 3.0.2 on 2020-04-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200222_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(default='', max_length=10),
        ),
    ]
