# Generated by Django 3.0.2 on 2020-02-18 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_profile_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
