# Generated by Django 3.0.2 on 2020-02-18 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200218_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='phone_Number',
        ),
    ]
